const places = [
  {
    //accommodations
    id: "acc1",
    name: "DoubleTree by Hilton Putrajaya Lakeside",
    location: "Putrajaya",
    rating: 4,
    price: "Moderate",
    image: "../assets/Accommodation/DoubleTree.png",
    co2: "15 kg CO₂ saved",
    type: "Accommodation",
    description: "5-star accommodations within 4 acres of landscaped grounds along Putrajaya Lake. Decorated in distinct ethnic themes, rooms offer the comfort of spacious layouts and flat-screen TVs. ",
    tags: ["Reduce Food Waste", "Water Conservation", "Energy Efficiency"]
  },
  {
    id: "acc2",
    name: "Pulse Grande Hotel",
    location: "Putrajaya",
    rating: 3,
    price: "Moderate",
    image: "../assets/Accommodation/PulsarGrande.png",
    co2: "12 kg CO₂ saved",
    type: "Accommodation",
    description: "Nestled on a scenic hilltop, PULSE GRANDE Hotel is a serene retreat for solo travelers, offering panoramic views of Putrajaya, an elegant infinity pool, a rejuvenating spa and direct access to botanical gardens for relaxation and exploration.",
    tags: ["Natural Ventilation", "Green Surroundings"]
  },
  {
    id: "acc3",
    name: "Zenith Putrajaya",
    location: "Putrajaya",
    rating: 3,
    price: "Premium",
    image: "../assets/Accommodation/Zenith.png",
    co2: "12 kg CO₂ saved",
    type: "Accommodation",
    description: "Zenith Hotel Putrajaya in Putrajaya offers a 5-star experience with a rooftop swimming pool, spa facilities, sauna, fitness centre, restaurant, bar, and free WiFi.",
    tags: ["Smart Energy Management", "Efficient Lighting"]
  },
  {
    id: "acc4",
    name: "Le Meridian Putrajaya",
    location: "Putrajaya",
    rating: 3,
    price: "Premium",
    image: "../assets/Accommodation/LeMeridian.png",
    co2: "12 kg CO₂ saved",
    type: "Accommodation",
    description: "Nestled on a scenic hilltop, PULSE GRANDE Hotel is a serene retreat for solo travelers, offering panoramic views of Putrajaya, an elegant infinity pool, a rejuvenating spa and direct access to botanical gardens for relaxation and exploration.",
    tags: ["Energy-Saving System", "Waste Reduction"]
  },
  {
    id: "acc5",
    name: "Uptown Eco Hotel",
    location: "Kuala Terengganu",
    rating: 3,
    price: "Budget",
    image: "../assets/Accommodation/UptownEcoHotel.png",
    co2: "12 kg CO₂ saved",
    type: "Accommodation",
    description: "Budget eco-themed hotel near Chinatown focusing on simple and low-impact stays.",
    tags: ["Minimal Waste Concept", "Energy-Saving Lighting"]
  },
  {
    id: "acc6",
    name: "Taaras Beach & Spa Resort",
    location: "Kuala Terengganu",
    rating: 4,
    price: "Premium",
    image: "../assets/Accommodation/TaarasResort.png",
    co2: "15 kg CO₂ saved",
    type: "Accommodation",
    description: "High-end resort promoting marine and environmental awareness.",
    tags: ["Marine Conservation", "Sustainable Tourism Practices"]
  },
  {
    id: "acc7",
    name: "Summer Bay Lang Tengah Island Resort",
    location: "Kuala Terengganu",
    rating: 4,
    price: "Premium",
    image: "../assets/Accommodation/SummerBay.png",
    co2: "15 kg CO₂ saved",
    type: "Accommodation",
    description: "Conveniently situated in the Lang Tengah part of Lang Tengah, this property puts you close to attractions and interesting dining options.",
    tags: ["Low-density Development", "Waste Management", "Eco Activities"]
  },
  {
    id: "acc8",
    name: "Duyong Marina Resort",
    location: "Kuala Terengganu",
    rating: 3,
    price: "Premium",
    image: "../assets/Accommodation/DuyongMarina.png",
    co2: "12 kg CO₂ saved",
    type: "Accommodation",
    description: "Duyong Marina & Resort is located in Palau Duyong, a 7-minute drive to Kuala Terengganu International Airport. The resort features an outdoor pool, fitness room and free Wi-Fi.",
    tags: ["Basic Resources", "Natural Surroundings"]
  },
  {
    id: "acc9",
    name: "Casa del Rio Melaka",
    location: "Bandaraya Melaka",
    rating: 4,
    price: "Premium",
    image: "../assets/Accommodation/CasaDelRio.png",
    co2: "12 kg CO₂ saved",
    type: "Accommodation",
    description: "Heritage hotel with sustainability initiatives.",
    tags: ["Water-saving Systems", "Eco-friendly Materials"]
  },
  {
    id: "acc10",
    name: "The Shore Hotel & Residences",
    location: "Bandaraya Melaka",
    rating: 3,
    price: "Moderate",
    image: "../assets/Accommodation/TheShore.png",
    co2: "10 kg CO₂ saved",
    type: "Accommodation",
    description: "Modern stay with efficient building systems.",
    tags: ["Energy Efficiency", "Reduced Plastic"]
  },
  {
    id: "acc11",
    name: "Hatten Hotel Melaka",
    location: "Bandaraya Melaka",
    rating: 3,
    price: "Moderate",
    image: "../assets/Accommodation/HattenHotel.png",
    co2: "9 kg CO₂ saved",
    type: "Accommodation",
    description: "Large hotel with basic sustainability practices.",
    tags: ["Energy-saving Lighting", "Water Conservation"]
  },
  {
    id: "acc12",
    name: "Liu Men",
    location: "Bandaraya Melaka",
    rating: 4,
    price: "Premium",
    image: "../assets/Accommodation/LiuMen.png",
    co2: "11 kg CO₂ saved",
    type: "Accommodation",
    description: "Heritage-focused boutique stay with adaptive reuse concept.",
    tags: ["Building Reuse", "Reduced Material Waste"]
  },
  {
    id: "acc13",
    name: "The Datai Langkawi",
    location: "Langkawi",
    rating: 5,
    price: "Premium",
    image: "../assets/Accommodation/TheDatai.png",
    co2: "20 kg CO₂ saved",
    type: "Accommodation",
    description: "Luxury eco-resort in a 10-million-year-old rainforest with strong sustainability initiatives.",
    tags: ["Rainforest Conservation", "Coral Reef Restoration", "No Plastic"]
  },
  {
    id: "acc14",
    name: "Ambong Rainforest Retreat",
    location: "Langkawi",
    rating: 5,
    price: "Premium",
    image: "../assets/Accommodation/AmbongRainforest.png",
    co2: "18 kg CO₂ saved",
    type: "Accommodation",
    description: "Boutique rainforest retreat with low-impact design and strong sustainability focus.",
    tags: ["Minimal Land Clearing", "Local Sourcing", "Eco-conscious Operations"]
  },
  {
    id: "acc15",
    name: "The Frangipani Langkawi Resort & Spa",
    location: "Langkawi",
    rating: 5,
    price: "Moderate",
    image: "../assets/Accommodation/TheFrangipani.png",
    co2: "17 kg CO₂ saved",
    type: "Accommodation",
    description: "Award-winning eco-resort with sustainable initiatives and beachfront chalets.",
    tags: ["Solar Panels", "Wastewater Recycling", "Organic Garden", "Plastic Reduction"]
  },
  {
    id: "acc16",
    name: "Berjaya Langkawi Resort",
    location: "Langkawi",
    rating: 4,
    price: "Premium",
    image: "../assets/Accommodation/BerjayaLangkawi.png",
    co2: "16 kg CO₂ saved",
    type: "Accommodation",
    description: "Beachfront resort offering nature activities and eco-tourism experiences.",
    tags: ["Forest Conservation", "Eco-tourism", "Wildlife Awareness"]
  },
    //Restaurants
  {
    id: "res1",
    name: "BMS Organics",
    location: "Putrajaya",
    rating: 5,
    price: "Moderate",
    image: "../assets/Restaurant/BMS.png",
    co2: "10 kg CO₂ saved",
    type: "Restaurant",
    description: "A plant-based cafe promoting holistic living with organic meals and beverages.",
    tags: ["Organic Ingredients", "Plant-based", "Sustainable Sourcing"]
  },
  {
    id: "res2",
    name: "Salad Atelier",
    location: "Putrajaya",
    rating: 5,
    price: "Moderate",
    image: "../assets/Restaurant/SaladAtelier.png",
    co2: "9 kg CO₂ saved",
    type: "Restaurant",
    description: "Healthy fast-casual restaurant offering customizable salads and poke bowls.",
    tags: ["Local Sourcing", "Healthy Food", "Low Processing"]
  },
  {
    id: "res3",
    name: "Summer Palace Restaurant",
    location: "Putrajaya",
    rating: 3,
    price: "Premium",
    image: "../assets/Restaurant/SummerPalace.png",
    co2: "8 kg CO₂ saved",
    type: "Restaurant",
    description: "Upscale Chinese dining with focus on seasonal and mindful ingredients.",
    tags: ["Seasonal Ingredients", "Local Sourcing"]
  },
  {
    id: "res4",
    name: "Cili Kampung",
    location: "Putrajaya",
    rating: 3,
    price: "Moderate",
    image: "../assets/Restaurant/CiliKampung.png",
    co2: "8 kg CO₂ saved",
    type: "Restaurant",
    description: "Traditional Malay cuisine using locally sourced ingredients.",
    tags: ["Local Ingredients", "Support Local Farming"]
  },
  {
    id: "res5",
    name: "Kenny Hills Bakers",
    location: "Putrajaya",
    rating: 3,
    price: "Moderate",
    image: "../assets/Restaurant/KennyHills.png",
    co2: "9 kg CO₂ saved",
    type: "Restaurant",
    description: "Artisanal bakery known for organic ingredients and small-batch baking.",
    tags: ["Organic Ingredients", "Artisanal Production"]
  },
  {
    id: "res6",
    name: "Rasa MamaKim Wellness Kitchen",
    location: "Kuala Terengganu",
    rating: 5,
    price: "Moderate",
    image: "../assets/Restaurant/MamaKim.png",
    co2: "9 kg CO₂ saved",
    type: "Restaurant",
    description: "Health-focused eatery promoting balanced nutrition and clean eating.",
    tags: ["Healthy Eating", "Low Processing", "Sustainable Diet"]
  },
  {
    id: "res7",
    name: "Chef Wan Meatless Cuisine",
    location: "Kuala Terengganu",
    rating: 3,
    price: "Moderate",
    image: "../assets/Restaurant/ChefWanCuisine.png",
    co2: "8 kg CO₂ saved",
    type: "Restaurant",
    description: "Meat-free restaurant offering local-inspired plant-based dishes.",
    tags: ["Plant-based", "Low Carbon Diet"]
  },
  {
    id: "res8",
    name: "Happy Vegetarian Restaurant",
    location: "Kuala Terengganu",
    rating: 3,
    price: "Budget",
    image: "../assets/Restaurant/HappyVegetarian.png",
    co2: "7 kg CO₂ saved",
    type: "Restaurant",
    description: "Affordable vegetarian restaurant with simple, traditional dishes.",
    tags: ["Vegetarian", "Low Impact", "Simple Cooking"]
  },
  {
    id: "res9",
    name: "MR Celup Tepung Station",
    location: "Kuala Terengganu",
    rating: 3,
    price: "Budget",
    image: "../assets/Restaurant/MCTS.png",
    co2: "7 kg CO₂ saved",
    type: "Restaurant",
    description: "Beachside eatery offering fresh local seafood in a traditional setting.",
    tags: ["Local Sourcing", "Low Processing"]
  },
  {
    id: "res10",
    name: "Botanist Veggie Cafe",
    location: "Bandaraya Melaka",
    rating: 5,
    price: "Moderate",
    image: "../assets/Restaurant/Botanist.png",
    co2: "9 kg CO₂ saved",
    type: "Restaurant",
    description: "Modern vegetarian cafe with diverse plant-based menu.",
    tags: ["Plant-based", "Organic Options"]
  },
  {
    id: "res11",
    name: "Green Reaper Vegetarian Eatery",
    location: "Bandaraya Melaka",
    rating: 5,
    price: "Premium",
    image: "../assets/Restaurant/TheGreenReaper.png",
    co2: "10 kg CO₂ saved",
    type: "Restaurant",
    description: "Botanical-themed vegetarian dining with eco-conscious concept.",
    tags: ["Plant-based", "Eco Awareness"]
  },
  {
    id: "res12",
    name: "Greenbite Cafe",
    location: "Bandaraya Melaka",
    rating: 3,
    price: "Budget",
    image: "../assets/Restaurant/GreenBite.png",
    co2: "7 kg CO₂ saved",
    type: "Restaurant",
    description: "Cozy vegetarian cafe offering simple healthy meals.",
    tags: ["Vegetarian", "Low Impact"]
  },
  {
    id: "res13",
    name: "Wild Coriander Melaka",
    location: "Bandaraya Melaka",
    rating: 3,
    price: "Moderate",
    image: "../assets/Restaurant/WildCoriander.png",
    co2: "8 kg CO₂ saved",
    type: "Restaurant",
    description: "Authentic local cuisine with strong cultural heritage.",
    tags: ["Local Ingredients", "Heritage Preservation"]
  },
  {
    id: "res14",
    name: "The Daily Fix Cafe",
    location: "Bandaraya Melaka",
    rating: 3,
    price: "Moderate",
    image: "../assets/Restaurant/DailyFix.png",
    co2: "8 kg CO₂ saved",
    type: "Restaurant",
    description: "Heritage cafe known for local fusion dishes and rustic setting.",
    tags: ["Adaptive Reuse", "Local Ingredients"]
  },
  {
    id: "res15",
    name: "The Fat Frog",
    location: "Langkawi",
    rating: 5,
    price: "Moderate",
    image: "../assets/Restaurant/TheFatFrog.png",
    co2: "9 kg CO₂ saved",
    type: "Restaurant",
    description: "Eco-conscious cafe focusing on organic and vegetarian meals.",
    tags: ["Organic Food", "Plant-based"]
  },
  {
    id: "res16",
    name: "Pegaga Langkawi Vegan Experience",
    location: "Langkawi",
    rating: 5,
    price: "Premium",
    image: "../assets/Restaurant/PegagaLangkawi.png",
    co2: "10 kg CO₂ saved",
    type: "Restaurant",
    description: "Rainforest vegan dining with local-inspired plant-based dishes.",
    tags: ["Vegan", "Local Ingredients"]
  },
  {
    id: "res17",
    name: "Indiana Vegan Cafe Langkawi",
    location: "Langkawi",
    rating: 5,
    price: "Moderate",
    image: "../assets/Restaurant/Indiana.png",
    co2: "9 kg CO₂ saved",
    type: "Restaurant",
    description: "Vibrant vegan cafe offering healthy plant-based meals.",
    tags: ["Vegan", "Healthy Food"]
  },
  {
    id: "res18",
    name: "The Dining Room",
    location: "Langkawi",
    rating: 5,
    price: "Premium",
    image: "../assets/Restaurant/TheDiningRoom.png",
    co2: "11 kg CO₂ saved",
    type: "Restaurant",
    description: "Fine dining experience using locally sourced sustainable ingredients.",
    tags: ["Farm-to-table", "Local Sourcing"]
  },
  {
    id: "res19",
    name: "Ikan-Ikan",
    location: "Langkawi",
    rating: 3,
    price: "Premium",
    image: "../assets/Restaurant/IkanIkan.png",
    co2: "9 kg CO₂ saved",
    type: "Restaurant",
    description: "Traditional Malaysian seafood restaurant with local sourcing.",
    tags: ["Local Seafood", "Support Local"]
  },
    //Activities
  {
    id: "act1",
    name: "Putrajaya Wetlands Park",
    location: "Putrajaya",
    rating: 4,
    price: "Budget",
    image: "../assets/Activities/WetlandsPark.png",
    co2: "6 kg CO₂ saved",
    type: "Activity",
    description: "Large freshwater wetlands with bird watching and ecological learning.",
    tags: ["Conservation", "Wildlife Protection", "Low Impact"]
  },
  {
    id: "act2",
    name: "Putrajaya Lake Eco Cruise",
    location: "Putrajaya",
    rating: 4,
    price: "Moderate",
    image: "../assets/Activities/EcoCruise.png",
    co2: "7 kg CO₂ saved",
    type: "Activity",
    description: "Electric boat cruise offering scenic and eco-friendly sightseeing.",
    tags: ["Electric Boats", "Zero Emissions"]
  },
  {
    id: "act3",
    name: "Taman Botani Putrajaya",
    location: "Putrajaya",
    rating: 5,
    price: "Budget",
    image: "../assets/Activities/TamanBotani.png",
    co2: "5 kg CO₂ saved",
    type: "Activity",
    description: "Botanical garden with cycling and plant exploration areas.",
    tags: ["Conservation", "Cycling", "No Vehicles"]
  },
  {
    id: "act4",
    name: "Putrajaya Challenge Park",
    location: "Putrajaya",
    rating: 3,
    price: "Moderate",
    image: "../assets/Activities/ChallengePark.png",
    co2: "6 kg CO₂ saved",
    type: "Activity",
    description: "Adventure park with BMX and rock climbing activities.",
    tags: ["Non-motorized", "Low Impact"]
  },
  {
    id: "act5",
    name: "Pulau Kapas Turtle Conservation",
    location: "Kuala Terengganu",
    rating: 5,
    price: "Premium",
    image: "../assets/Activities/PulauKapas.png",
    co2: "10 kg CO₂ saved",
    type: "Activity",
    description: "Snorkeling and turtle conservation experience with protected habitats.",
    tags: ["Wildlife Conservation", "Guided Tours", "Low Impact"]
  },
  {
    id: "act6",
    name: "Sungai Terengganu Heritage Cruise",
    location: "Kuala Terengganu",
    rating: 3,
    price: "Moderate",
    image: "../assets/Activities/HeritageCruise.png",
    co2: "7 kg CO₂ saved",
    type: "Activity",
    description: "Cultural river cruise showcasing traditional villages and heritage.",
    tags: ["Cultural", "Low Impact"]
  },
  {
    id: "act7",
    name: "Setiu Wetlands Eco Safari",
    location: "Kuala Terengganu",
    rating: 5,
    price: "Premium",
    image: "../assets/Activities/WetlandsEcoSafari.png",
    co2: "10 kg CO₂ saved",
    type: "Activity",
    description: "Mangrove kayaking and wildlife exploration experience.",
    tags: ["Conservation", "Kayaking", "Low Impact"]
  },
  {
    id: "act8",
    name: "Muzium Negeri Terengganu",
    location: "Kuala Terengganu",
    rating: 4,
    price: "Budget",
    image: "../assets/Activities/MuseumComplex.png",
    co2: "6 kg CO₂ saved",
    type: "Activity",
    description: "Large museum showcasing cultural heritage and artifacts.",
    tags: ["Cultural Preservation", "Low Impact"]
  },
  {
    id: "act9",
    name: "Melaka River Eco Cruise",
    location: "Bandaraya Melaka",
    rating: 3,
    price: "Moderate",
    image: "../assets/Activities/MelakaRiverCruise.png",
    co2: "7 kg CO₂ saved",
    type: "Activity",
    description: "River cruise passing murals and heritage sites.",
    tags: ["Cultural", "Low Impact"]
  },
  {
    id: "act10",
    name: "Melaka Bird Park",
    location: "Bandaraya Melaka",
    rating: 4,
    price: "Moderate",
    image: "../assets/Activities/BirdPark.png",
    co2: "8 kg CO₂ saved",
    type: "Activity",
    description: "Walk-in aviary with diverse bird species and conservation focus.",
    tags: ["Wildlife Conservation", "Low Impact"]
  },
  {
    id: "act11",
    name: "Sungai Udang Mangrove Tour",
    location: "Bandaraya Melaka",
    rating: 5,
    price: "Premium",
    image: "../assets/Activities/MangroveTour.png",
    co2: "10 kg CO₂ saved",
    type: "Activity",
    description: "Firefly watching experience in mangrove forests.",
    tags: ["Conservation", "Eco Tourism"]
  },
  {
    id: "act12",
    name: "Heritage Walk Trail",
    location: "Bandaraya Melaka",
    rating: 4,
    price: "Budget",
    image: "../assets/Activities/HeritageWalkTrail.png",
    co2: "5 kg CO₂ saved",
    type: "Activity",
    description: "Walking tour through Melaka’s historical landmarks.",
    tags: ["Walking", "Heritage Preservation"]
  },
  {
    id: "act13",
    name: "Kilim Geoforest Park Tour",
    location: "Langkawi",
    rating: 5,
    price: "Premium",
    image: "../assets/Activities/GeoforestParkTour.png",
    co2: "11 kg CO₂ saved",
    type: "Activity",
    description: "Boat safari through mangroves and limestone formations.",
    tags: ["Geopark", "Conservation"]
  },
  {
    id: "act14",
    name: "Langkawi SkyBridge",
    location: "Langkawi",
    rating: 4,
    price: "Premium",
    image: "../assets/Activities/LangkawiSkybridge.png",
    co2: "9 kg CO₂ saved",
    type: "Activity",
    description: "Cable car and bridge offering panoramic rainforest views.",
    tags: ["Eco Tourism", "Low Impact"]
  },
  {
    id: "act16",
    name: "Black Sand Beach Trail",
    location: "Langkawi",
    rating: 4,
    price: "Budget",
    image: "../assets/Activities/BlackSandBeach.png",
    co2: "5 kg CO₂ saved",
    type: "Activity",
    description: "Nature walk along unique black sand beach.",
    tags: ["Nature", "Low Impact"]
  },
  {
    id: "act17",
    name: "Langkawi Wildlife Park",
    location: "Langkawi",
    rating: 4,
    price: "Moderate",
    image: "../assets/Activities/WildlifePark.png",
    co2: "8 kg CO₂ saved",
    type: "Activity",
    description: "Interactive wildlife park with conservation programs.",
    tags: ["Animal Conservation", "Education"]
  }
];